name: Code Style

on:
  pull_request:
    branches: [ main ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: gmp, mbstring, json
          coverage: none
          tools: php-cs-fixer:3.95.18

      - name: Run PHP CS Fixer
        run: php-cs-fixer fix --dry-run --diff --verbose
